package com.paulchibamba.margin.domain.progress

object FactKey {
    const val BOOK = "book"
    const val CHAPTER = "chapter"
    const val CONCEPT = "concept"
    const val CONCEPTS = "concepts"
    const val SUMMARY = "summary"
    const val INTRODUCED = "introduced"
    const val REMEMBERED = "remembered"
    const val TOTAL = "total"
    const val REMAINING = "remaining"
    const val NEXT = "next"
    const val THRESHOLD = "threshold"
    const val REREAD_CONCEPT = "rereadConcept"
    const val OLDER_CONCEPT = "olderConcept"
    const val DAYS_AGO = "daysAgo"
    const val DATE = "date"
    const val FAIL_COUNT = "failCount"
    const val PASS_COUNT = "passCount"
    const val NOTES_AWAY = "notesAway"
    const val SECTION = "section"
    const val KNOWN_CONCEPT = "knownConcept"
    const val WIN = "win"
    const val SCOPE = "scope"
    const val NAME = "name"
    const val MILESTONE = "milestone"
    const val DAYS = "days"
    const val TRIGGER = "trigger"
    const val ANGLES_SHOWN = "anglesShown"
    const val ANCHOR = "anchor"
}
